name: CI Auto Update

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '59 23 * * *'

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d .

  checkers:
    name: Run checkers
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Install git on container
        run: |
          apt-get update
          apt-get install -y git python3.12
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3.12 ./vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3.12 ./vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs:
      - checkers
      - lint-vala

    container:
      image: ubuntu:latest

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3.12 valac meson ninja-build libgee-0.8-dev libglib2.0-dev libsoup-3.0-dev libjson-glib-dev gobject-introspection
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build -Dprefix=/usr

      - name: Build
        run: meson compile -C _build

  # update:
  #   name: Update&Push
  #   runs-on: ubuntu-latest
  #   needs: test-build

  #   container:
  #     image: ubuntu:latest

  #   steps:
  #     - name: Install libs on container
  #       run: |
  #         apt-get update
  #         apt-get install -y git python3.12

  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       run: sh auto-update/update.sh

  #     - name: Setup
  #       run: |
  #         git config --global user.email "auto-updater@users.noreply.github.com"
  #         git config --global user.name "auto-updater" 

  #     - name: Push
  #       run: |
  #         chmod -R 744 .
  #         git add ./lib/*
  #         git commit -m "Update
  #         git push
